### PR TITLE
scanner imprvement : NFM, AM and FM

### PR DESCRIPTION
**Pull request by alain00091**
based on portapack mayhem 1.1.0

1 : 3 scanners applications:    NFM as before, FM and AM
2:  use default files    SCANNER_AM.TXT/SCANNER_FM.TXT and SCANNER_NFM.TXT
3: do not read old file SCANNER.TXT
4: added RSSI bargraph
5: fix issue with WAIT parameter: now if a station has a signal better than Squelch, it stops scanning for WAIT time (second) and restart scanning
6: if WAIT equal 99, it stays indefinitely on the last good station (Signal > Squelch)
7: support up to 250 differents frequencies ( total of RANGE and SINGLE) , tested !
8: if any, show the description of the frequency and Single/Range
9: if there is no file like SCANNER_AM.TXT, it will using default frequency (hard coded) and print "no file ...".
If someone wants to add default frequencies you are welcome !
10: in freq manager added a step for Range freq: if no step after the description it will use default step
          10 k for am, 100k for fm and 12.5 k for NFM
11: steps are   :     s=1 to s=8 now , so 10khz,9khz,12,5khz,6,25khz,100khz,50khz,25khz,,250khz

SCR_0000
SCR_0001
SCR_0002
SCR_0003
SCR_0004
SCR_0009

### CODE REVIEW

**Comment by eried** [comment]
hi @alain00091 I do not think it is possible to accept a PR like this 😂 it is too many changes

**Comment by alain00091** [comment]
PR is for bugs only and/or new features ?

**Comment by eried** [comment]
PR can be for bugs or new features, but the owner of the repo needs to check that it does not break anything. So you can see that if you have 600+ commits and files changed, nobody will be able to humanly be sure that everything is correct. Also you need to match the phylosophy of the project. I dont think this original firmware is intended to do any Transmit. 

I recommend to you to do small incremental changes and try to push a small improvement first, 2-4 commits with few changes in some files to start grasping the idea of how to collaborate.

**Comment by alain00091** [comment]
Ok I will do,    I do not remember if I wrote it but I took your release 1.1.0 (fork) and upgrade it with lot of tests before publishing it

**Comment by eried** [comment]
Then maybe you created a pull request in the wrong place 🕵️‍♂️ this is the original portapack firmware, Check on top:
image

**Comment by jboone** [comment]
Development has been taking place in the Mayhem fork for years now. This repo will be archived shortly.

**Pull request closed without merging**
