### PR TITLE
Added PortaPack Button Location

### PR DESCRIPTION
**Pull request by JDogHerman**
once merged I'll put a request to use it in the wiki documentation.

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
bump, please do

**Comment by ne1** [comment]
Hi,

here is the FreeCad File - Maybe it is helpful (even if the quality is poor) :) 

Greetings

**Comment by JDogHerman** [comment]
Sorry on the delay on this. I changed machines and I am trying to find the original picture so I can modify it. I will look for it this weekend.

**Comment by dominicgs** [comment]
You can use this image if you like: https://dominicspill.com/images/Portapack_buttons.jpg

**Comment by jboone** [comment]
Development has been taking place in the Mayhem fork for years now. This repo will be archived shortly.

**Pull request closed without merging**
